"""Steam Manager Test Expected Outputs."""

import datetime

EXPECTED_OUTPUT = [
    {
        "open_date": datetime.date(2024, 1, 1),
        "close_date": None,
        "trades": [
            {
                "trade_date": datetime.date(2024, 1, 1),
                "value_date": datetime.date(2025, 1, 1),
                "message": [],
                "underlying": "GOLD",
                "direction": "Buy",
                "instrument_type": "Put",
                "asset_class": "CM",
                "premium": 0,
                "strike": None,
                "strike_calculation": "abs",
            },
            {
                "trade_date": datetime.date(2024, 1, 1),
                "value_date": datetime.date(2025, 1, 1),
                "message": [],
                "underlying": "GOLD",
                "direction": "Sell",
                "instrument_type": "Call",
                "asset_class": "CM",
                "premium": 0,
                "strike": None,
                "strike_calculation": "abs",
            },
        ],
    },
    {
        "open_date": datetime.date(2024, 2, 1),
        "close_date": None,
        "trades": [
            {
                "trade_date": datetime.date(2024, 2, 1),
                "value_date": datetime.date(2025, 2, 1),
                "message": [],
                "underlying": "GOLD",
                "direction": "Buy",
                "instrument_type": "Put",
                "asset_class": "CM",
                "premium": 0,
                "strike": None,
                "strike_calculation": "abs",
            },
            {
                "trade_date": datetime.date(2024, 2, 1),
                "value_date": datetime.date(2025, 2, 1),
                "message": [],
                "underlying": "GOLD",
                "direction": "Sell",
                "instrument_type": "Call",
                "asset_class": "CM",
                "premium": 0,
                "strike": None,
                "strike_calculation": "abs",
            },
        ],
    },
    {
        "open_date": datetime.date(2024, 3, 1),
        "close_date": None,
        "trades": [
            {
                "trade_date": datetime.date(2024, 3, 1),
                "value_date": datetime.date(2025, 3, 1),
                "message": [],
                "underlying": "GOLD",
                "direction": "Buy",
                "instrument_type": "Put",
                "asset_class": "CM",
                "premium": 0,
                "strike": None,
                "strike_calculation": "abs",
            },
            {
                "trade_date": datetime.date(2024, 3, 1),
                "value_date": datetime.date(2025, 3, 1),
                "message": [],
                "underlying": "GOLD",
                "direction": "Sell",
                "instrument_type": "Call",
                "asset_class": "CM",
                "premium": 0,
                "strike": None,
                "strike_calculation": "abs",
            },
        ],
    },
    {
        "open_date": datetime.date(2024, 4, 1),
        "close_date": None,
        "trades": [
            {
                "trade_date": datetime.date(2024, 4, 1),
                "value_date": datetime.date(2025, 4, 1),
                "message": [],
                "underlying": "GOLD",
                "direction": "Buy",
                "instrument_type": "Put",
                "asset_class": "CM",
                "premium": 0,
                "strike": None,
                "strike_calculation": "abs",
            },
            {
                "trade_date": datetime.date(2024, 4, 1),
                "value_date": datetime.date(2025, 4, 1),
                "message": [],
                "underlying": "GOLD",
                "direction": "Sell",
                "instrument_type": "Call",
                "asset_class": "CM",
                "premium": 0,
                "strike": None,
                "strike_calculation": "abs",
            },
        ],
    },
    {
        "open_date": datetime.date(2024, 5, 1),
        "close_date": None,
        "trades": [
            {
                "trade_date": datetime.date(2024, 5, 1),
                "value_date": datetime.date(2025, 5, 1),
                "message": [],
                "underlying": "GOLD",
                "direction": "Buy",
                "instrument_type": "Put",
                "asset_class": "CM",
                "premium": 0,
                "strike": None,
                "strike_calculation": "abs",
            },
            {
                "trade_date": datetime.date(2024, 5, 1),
                "value_date": datetime.date(2025, 5, 1),
                "message": [],
                "underlying": "GOLD",
                "direction": "Sell",
                "instrument_type": "Call",
                "asset_class": "CM",
                "premium": 0,
                "strike": None,
                "strike_calculation": "abs",
            },
        ],
    },
    {
        "open_date": datetime.date(2024, 6, 1),
        "close_date": None,
        "trades": [
            {
                "trade_date": datetime.date(2024, 6, 1),
                "value_date": datetime.date(2025, 6, 1),
                "message": [],
                "underlying": "GOLD",
                "direction": "Buy",
                "instrument_type": "Put",
                "asset_class": "CM",
                "premium": 0,
                "strike": None,
                "strike_calculation": "abs",
            },
            {
                "trade_date": datetime.date(2024, 6, 1),
                "value_date": datetime.date(2025, 6, 1),
                "message": [],
                "underlying": "GOLD",
                "direction": "Sell",
                "instrument_type": "Call",
                "asset_class": "CM",
                "premium": 0,
                "strike": None,
                "strike_calculation": "abs",
            },
        ],
    },
    {
        "open_date": datetime.date(2024, 7, 1),
        "close_date": None,
        "trades": [
            {
                "trade_date": datetime.date(2024, 7, 1),
                "value_date": datetime.date(2025, 7, 1),
                "message": [],
                "underlying": "GOLD",
                "direction": "Buy",
                "instrument_type": "Put",
                "asset_class": "CM",
                "premium": 0,
                "strike": None,
                "strike_calculation": "abs",
            },
            {
                "trade_date": datetime.date(2024, 7, 1),
                "value_date": datetime.date(2025, 7, 1),
                "message": [],
                "underlying": "GOLD",
                "direction": "Sell",
                "instrument_type": "Call",
                "asset_class": "CM",
                "premium": 0,
                "strike": None,
                "strike_calculation": "abs",
            },
        ],
    },
    {
        "open_date": datetime.date(2024, 8, 1),
        "close_date": None,
        "trades": [
            {
                "trade_date": datetime.date(2024, 8, 1),
                "value_date": datetime.date(2025, 8, 1),
                "message": [],
                "underlying": "GOLD",
                "direction": "Buy",
                "instrument_type": "Put",
                "asset_class": "CM",
                "premium": 0,
                "strike": None,
                "strike_calculation": "abs",
            },
            {
                "trade_date": datetime.date(2024, 8, 1),
                "value_date": datetime.date(2025, 8, 1),
                "message": [],
                "underlying": "GOLD",
                "direction": "Sell",
                "instrument_type": "Call",
                "asset_class": "CM",
                "premium": 0,
                "strike": None,
                "strike_calculation": "abs",
            },
        ],
    },
    {
        "open_date": datetime.date(2024, 9, 1),
        "close_date": None,
        "trades": [
            {
                "trade_date": datetime.date(2024, 9, 1),
                "value_date": datetime.date(2025, 9, 1),
                "message": [],
                "underlying": "GOLD",
                "direction": "Buy",
                "instrument_type": "Put",
                "asset_class": "CM",
                "premium": 0,
                "strike": None,
                "strike_calculation": "abs",
            },
            {
                "trade_date": datetime.date(2024, 9, 1),
                "value_date": datetime.date(2025, 9, 1),
                "message": [],
                "underlying": "GOLD",
                "direction": "Sell",
                "instrument_type": "Call",
                "asset_class": "CM",
                "premium": 0,
                "strike": None,
                "strike_calculation": "abs",
            },
        ],
    },
    {
        "open_date": datetime.date(2024, 10, 1),
        "close_date": None,
        "trades": [
            {
                "trade_date": datetime.date(2024, 10, 1),
                "value_date": datetime.date(2025, 10, 1),
                "message": [],
                "underlying": "GOLD",
                "direction": "Buy",
                "instrument_type": "Put",
                "asset_class": "CM",
                "premium": 0,
                "strike": None,
                "strike_calculation": "abs",
            },
            {
                "trade_date": datetime.date(2024, 10, 1),
                "value_date": datetime.date(2025, 10, 1),
                "message": [],
                "underlying": "GOLD",
                "direction": "Sell",
                "instrument_type": "Call",
                "asset_class": "CM",
                "premium": 0,
                "strike": None,
                "strike_calculation": "abs",
            },
        ],
    },
    {
        "open_date": datetime.date(2024, 11, 1),
        "close_date": None,
        "trades": [
            {
                "trade_date": datetime.date(2024, 11, 1),
                "value_date": datetime.date(2025, 11, 1),
                "message": [],
                "underlying": "GOLD",
                "direction": "Buy",
                "instrument_type": "Put",
                "asset_class": "CM",
                "premium": 0,
                "strike": None,
                "strike_calculation": "abs",
            },
            {
                "trade_date": datetime.date(2024, 11, 1),
                "value_date": datetime.date(2025, 11, 1),
                "message": [],
                "underlying": "GOLD",
                "direction": "Sell",
                "instrument_type": "Call",
                "asset_class": "CM",
                "premium": 0,
                "strike": None,
                "strike_calculation": "abs",
            },
        ],
    },
    {
        "open_date": datetime.date(2024, 12, 1),
        "close_date": None,
        "trades": [
            {
                "trade_date": datetime.date(2024, 12, 1),
                "value_date": datetime.date(2025, 12, 1),
                "message": [],
                "underlying": "GOLD",
                "direction": "Buy",
                "instrument_type": "Put",
                "asset_class": "CM",
                "premium": 0,
                "strike": None,
                "strike_calculation": "abs",
            },
            {
                "trade_date": datetime.date(2024, 12, 1),
                "value_date": datetime.date(2025, 12, 1),
                "message": [],
                "underlying": "GOLD",
                "direction": "Sell",
                "instrument_type": "Call",
                "asset_class": "CM",
                "premium": 0,
                "strike": None,
                "strike_calculation": "abs",
            },
        ],
    },
]
